"""ROS 2 bridge node used by the teach pendant GUI.

This is the single rclpy node the GUI owns. It mirrors the proven wiring from
the project's ``drawing_ui_node`` (jog / set / home / freeze + drawing) and
adds the teach-pendant extras: Cartesian jog via ``/ee_target``, named pose
presets, live status (joint positions + end-effector pose), and an E-stop that
freezes the arm and stops feeding any motion targets.
"""

from __future__ import annotations

import json
import math
import os
import glob
import signal
import subprocess

import rclpy
from rclpy.node import Node
from builtin_interfaces.msg import Duration
from std_msgs.msg import String
from sensor_msgs.msg import JointState
from geometry_msgs.msg import PoseArray, Pose, PoseStamped, Point
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint


JOINT_NAMES = [
    "joint_1", "joint_2", "joint_3", "joint_4",
    "joint_5", "joint_6", "joint_7",
]
# "Home" button = all joints at zero (per user request). NB this is the
# straight-out, near-singular pose, so jogging/drawing FROM it can be poorly
# conditioned — it's a parking/reset target, not the operating pose. (The
# backend still BOOTS to the conditioned elbow-up go_to_start pose
# [0,-0.4,0,1.2,0,0,0] in pendant_backend.launch.py; that is separate.)
HOME_JOINTS = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
JOG_STEP_RAD = 0.1
JOG_DURATION_S = 0.5

# Soft joint limits kept just inside the URDF hard limits (matches
# drawing_ui_node). ``None`` = continuous joint.
LIMIT_MARGIN_RAD = 0.05
JOINT_LIMITS = [
    None,            # joint_1 — continuous
    (-1.6, 1.6),     # joint_2
    None,            # joint_3 — continuous
    (-1.6, 1.6),     # joint_4
    None,            # joint_5 — continuous
    (-0.48, 0.26),   # joint_6 — narrow range
    (-1.6, 1.6),     # joint_7
]

# Nodes that DRIVE the arm — killed by the hard E-stop so the robot has no
# command source left (then re-run on RESET). These are the command-side
# drivers (their node names from pendant_backend.launch.py); the E-stop ALSO
# kills whatever publishes /joint_states (discovered live), to cover the real
# hardware where pos_motor_sub follows /joint_states. In sim the /joint_states
# publisher is Gazebo's broadcaster (no separate process → simply not found →
# skipped), and killing these command drivers is what stops the sim robot.
DRIVER_NODES = ("ik_7dof_v3", "ik_to_trajectory", "drawing_batch_planner")

# Named joint presets shown as buttons in the GUI.
PRESETS: dict[str, list[float]] = {
    "Home": list(HOME_JOINTS),
    "Ready": [0.0, 0.4, 0.0, -0.6, 0.0, 0.0, 0.0],
}

# Cartesian jog step (metres) and the frame targets are published in.
CART_STEP_M = 0.01
BASE_FRAME = "base_link"


# ── Reachable-workspace envelope for the position-only Cartesian jog ──────────
# Outer boundary r_max(z) of what the jog IK (ik_7dof_v3 with elbow-up soft
# limits) can reach, where r = hypot(x, y). The arm is axisymmetric about z
# (continuous joint_1 → full 360°), so this 2-D (r, z) boundary fully describes
# the reachable dome. Generated by workspace_creation/jog_envelope.py
# (URDF FK + the jog soft-limits, 400k samples) — REGENERATE + repaste if the
# soft limits in pendant_backend.launch.py change.
_WS_Z_MIN = -0.152
_WS_Z_MAX = 0.6072
_WS_Z_KNOTS = [-0.1384, -0.1113, -0.0842, -0.0571, -0.03, -0.0028, 0.0243,
               0.0514, 0.0785, 0.1056, 0.1327, 0.1598, 0.1869, 0.2141, 0.2412,
               0.2683, 0.2954, 0.3225, 0.3496, 0.3767, 0.4039, 0.431, 0.4581,
               0.4852, 0.5123, 0.5394, 0.5665, 0.5936]
_WS_R_MAX = [0.3383, 0.3818, 0.4186, 0.4361, 0.4557, 0.4721, 0.4795, 0.4876,
             0.4909, 0.4925, 0.4922, 0.491, 0.4889, 0.4843, 0.4793, 0.4719,
             0.4623, 0.4521, 0.4395, 0.4254, 0.4071, 0.3873, 0.3654, 0.338,
             0.3085, 0.2699, 0.2255, 0.1591]
# Keep clamped targets this far inside the boundary — right at the edge the IK
# can stall, so leave it a little reachable headroom.
_WS_MARGIN_M = 0.01


def reach_r_max(z: float) -> float:
    """Max reachable horizontal radius at height z (linear interp on the
    sampled dome boundary; clamped past the ends)."""
    ks = _WS_Z_KNOTS
    if z <= ks[0]:
        return _WS_R_MAX[0]
    if z >= ks[-1]:
        return _WS_R_MAX[-1]
    for i in range(1, len(ks)):
        if z <= ks[i]:
            t = (z - ks[i - 1]) / (ks[i] - ks[i - 1])
            return _WS_R_MAX[i - 1] + t * (_WS_R_MAX[i] - _WS_R_MAX[i - 1])
    return _WS_R_MAX[-1]


def clamp_joint(idx: int, value: float) -> float:
    lim = JOINT_LIMITS[idx]
    if lim is None:
        return value
    lo, hi = lim
    return max(lo + LIMIT_MARGIN_RAD, min(hi - LIMIT_MARGIN_RAD, value))


class PendantBridge(Node):
    def __init__(self) -> None:
        super().__init__("pendant7dof_bridge")

        # --- publishers ---------------------------------------------------
        self.traj_pub = self.create_publisher(
            JointTrajectory, "/arm_controller/joint_trajectory", 10
        )
        self.target_pub = self.create_publisher(PoseStamped, "/ee_target", 10)
        self.strokes_pub = self.create_publisher(String, "drawing/strokes", 10)
        # Publishing an empty PoseArray clears any in-flight drawing path so
        # its IK output stops fighting manual commands.
        self.path_pub = self.create_publisher(PoseArray, "/cartesian_path", 10)

        # --- state --------------------------------------------------------
        self._last_q = list(HOME_JOINTS)
        self._ee_pose: PoseStamped | None = None
        self._estopped = False
        self._killed_procs: list = []   # (argv, cwd) of nodes killed by E-stop, for RESET
        self._last_drawing: str | None = None
        # Internal Cartesian-jog target. Advances only while the robot keeps up;
        # if it falls behind (workspace edge / unreachable) the target re-anchors
        # to the actual pose so the joystick can't push it out of reach.
        self._cart_target: list[float] | None = None
        self._prev_cur: list[float] | None = None   # EE pos at the last jog tick
        self._cart_stall = 0                         # consecutive stalled ticks
        self._cart_stalled = False                   # latched: held at a limit
        self._stall_dir: list[float] | None = None   # jog dir when it stalled
        self._jog_moved_once = False                 # EE has moved since this jog began

        # --- subscriptions ------------------------------------------------
        self.create_subscription(JointState, "/joint_states", self._cb_state, 20)
        self.create_subscription(PoseStamped, "/ee_pose", self._cb_ee, 20)

        self._pen_cb = None
        self.create_subscription(Point, "/pen_canvas_norm", self._cb_pen, 30)

        self.get_logger().info("pendant7dof bridge ready")

    # ── callbacks ─────────────────────────────────────────────────────────
    def _cb_state(self, msg: JointState) -> None:
        if not msg.name or not msg.position:
            return
        for jn, p in zip(msg.name, msg.position):
            if jn in JOINT_NAMES:
                self._last_q[JOINT_NAMES.index(jn)] = float(p)

    def _cb_ee(self, msg: PoseStamped) -> None:
        self._ee_pose = msg

    def _cb_pen(self, msg: Point) -> None:
        if self._pen_cb is not None:
            self._pen_cb(float(msg.x), float(msg.y), float(msg.z))

    def attach_pen_callback(self, cb) -> None:
        self._pen_cb = cb

    # ── status accessors (read by the GUI) ────────────────────────────────
    def get_joint(self, idx: int) -> float:
        return float(self._last_q[idx])

    def get_joints(self) -> list[float]:
        return list(self._last_q)

    def get_ee_xyz(self) -> tuple[float, float, float] | None:
        if self._ee_pose is None:
            return None
        p = self._ee_pose.pose.position
        return (p.x, p.y, p.z)

    @property
    def estopped(self) -> bool:
        return self._estopped

    # ── motion helpers ────────────────────────────────────────────────────
    def _clear_path(self) -> None:
        empty = PoseArray()
        empty.header.stamp = self.get_clock().now().to_msg()
        empty.header.frame_id = BASE_FRAME
        self.path_pub.publish(empty)

    def _send_traj(self, positions: list[float], duration_s: float) -> None:
        traj = JointTrajectory()
        traj.joint_names = list(JOINT_NAMES)
        pt = JointTrajectoryPoint()
        pt.positions = list(positions)
        sec = int(duration_s)
        pt.time_from_start = Duration(
            sec=sec, nanosec=int((duration_s - sec) * 1e9)
        )
        traj.points.append(pt)
        self.traj_pub.publish(traj)
        self._last_q = list(positions)

    def jog_joint(self, idx: int, delta: float) -> None:
        if self._estopped:
            self.get_logger().warn("E-stop active — jog ignored")
            return
        self._clear_path()
        q = list(self._last_q)
        q[idx] = clamp_joint(idx, q[idx] + delta)
        self._send_traj(q, JOG_DURATION_S)
        self.get_logger().info(
            f"JOG {JOINT_NAMES[idx]} {delta:+.2f} -> {q[idx]:+.3f} rad"
        )

    def jog_joints(self, deltas: dict[int, float], duration_s: float = 0.18) -> None:
        """Jog several joints at once in a single trajectory. Used by the
        joystick, which streams small deltas at ~15 Hz; one trajectory per tick
        keeps the joints moving together instead of fighting."""
        if self._estopped or not deltas:
            return
        q = list(self._last_q)
        for idx, d in deltas.items():
            q[idx] = clamp_joint(idx, q[idx] + d)
        self._send_traj(q, duration_s)

    def set_joint(self, idx: int, target_rad: float, duration_s: float = 1.5) -> None:
        if self._estopped:
            self.get_logger().warn("E-stop active — set ignored")
            return
        self._clear_path()
        clamped = clamp_joint(idx, float(target_rad))
        if clamped != float(target_rad):
            self.get_logger().warn(
                f"{JOINT_NAMES[idx]}: {target_rad:+.3f} clamped to {clamped:+.3f}"
            )
        q = list(self._last_q)
        q[idx] = clamped
        self._send_traj(q, duration_s)

    def goto_preset(self, name: str, duration_s: float = 2.0) -> None:
        if self._estopped:
            self.get_logger().warn("E-stop active — preset ignored")
            return
        if name not in PRESETS:
            self.get_logger().warn(f"unknown preset '{name}'")
            return
        self._clear_path()
        self._send_traj(PRESETS[name], duration_s)
        self.get_logger().info(f"PRESET {name}")

    def send_home(self) -> None:
        self.goto_preset("Home")

    def stop_and_home(self) -> None:
        """Drawing-tab 'Reset': stop whatever the robot is doing (cancel the
        active drawing/jog so nothing keeps streaming the controller) and then
        move it Home. Blocked while E-stopped (goto_preset guards that)."""
        self._cart_jog_stop(force=True)   # stop the jog/draw IK from fighting
        self._clear_path()
        self.goto_preset("Home")

    def move_to_joints(self, positions, duration_s: float = 2.0) -> None:
        """Move to an arbitrary 7-joint configuration (used to recall a saved
        target)."""
        if self._estopped:
            self.get_logger().warn("E-stop active — move ignored")
            return
        if positions is None or len(positions) != 7:
            self.get_logger().warn("move_to_joints needs 7 positions")
            return
        self._clear_path()
        q = [clamp_joint(i, float(positions[i])) for i in range(7)]
        self._send_traj(q, duration_s)
        self.get_logger().info("MOVE to saved target")

    def cartesian_jog(self, axis: str, delta: float) -> None:
        """Nudge the end-effector target along a base-frame axis.

        Requires the IK node (consuming ``/ee_target``) and the FK node
        (publishing ``/ee_pose``) to be running so we have a current pose to
        offset from.
        """
        if self._estopped:
            self.get_logger().warn("E-stop active — cartesian jog ignored")
            return
        if self._ee_pose is None:
            self.get_logger().warn("no /ee_pose yet — is the FK node running?")
            return
        target = PoseStamped()
        target.header.stamp = self.get_clock().now().to_msg()
        target.header.frame_id = BASE_FRAME
        target.pose = self._ee_pose.pose  # copy current orientation + position
        if axis == "x":
            target.pose.position.x += delta
        elif axis == "y":
            target.pose.position.y += delta
        elif axis == "z":
            target.pose.position.z += delta
        else:
            self.get_logger().warn(f"unknown axis '{axis}'")
            return
        self.target_pub.publish(target)
        self.get_logger().info(f"CART {axis}{delta:+.3f} m")

    def _publish_ee_target(self, x: float, y: float, z: float) -> None:
        target = PoseStamped()
        target.header.stamp = self.get_clock().now().to_msg()
        target.header.frame_id = BASE_FRAME
        p = Pose()
        p.position.x, p.position.y, p.position.z = x, y, z
        p.orientation = self._ee_pose.pose.orientation  # hold current orientation
        target.pose = p
        self.target_pub.publish(target)

    # The commanded target leads the actual EE by at most CART_LEAD_M (m) so the
    # IK has enough error to drive motion. Two things keep that lead honest:
    #  • a MODEL-BASED workspace clamp (_clamp_target) projects the target into
    #    the reachable dome, so the joystick can never push /ee_target out of
    #    reach in the first place — boundary stalls are prevented, not patched.
    #  • the feedback STALL_* latch is the backstop: if the EE still stops
    #    advancing, we classify it (_at_workspace_boundary) and hold the
    #    reachable pose — a reach limit is a reach limit, the jog stops cleanly.
    CART_LEAD_M = 0.01
    STALL_FRAC = 0.25       # progress < this × commanded step ⇒ a stalled tick
    STALL_TICKS = 4         # consecutive stalled ticks ⇒ latch (held at limit)
    UNSTALL_DOT = 0.5       # steer >60° off the stalled dir ⇒ release the latch

    def cartesian_jog_xyz(self, dx: float, dy: float, dz: float) -> None:
        """Stream an EE target from the joystick (~15 Hz), integrating stick
        deflection into an internal target that leads the actual pose. The
        target is clamped into the reachable dome so it can't be pushed out of
        reach; if the EE still stalls, the pose is held cleanly."""
        if self._estopped or self._ee_pose is None:
            return
        if dx == 0.0 and dy == 0.0 and dz == 0.0:
            # Stick centered / released: stop leading the target and re-anchor it
            # to the actual pose so the live jog IK reaches it and DEACTIVATES.
            # Otherwise the last ~1 cm lead (or an unreachable lead at a reach
            # limit) keeps ik_arm_v3 perpetually active, streaming /joint_commands
            # -> ik_to_trajectory -> /arm_controller/joint_trajectory at ~50 Hz,
            # which then preempts any drawing trajectory ~50x/s (the twitch).
            self._cart_jog_stop()
            return
        p = self._ee_pose.pose.position
        cur = [p.x, p.y, p.z]
        if self._cart_target is None:
            self._cart_target = list(cur)
            self._jog_moved_once = False   # fresh jog: wait for the IK to engage

        step = math.sqrt(dx * dx + dy * dy + dz * dz)
        d_unit = [dx / step, dy / step, dz / step]
        if self._prev_cur is not None:
            moved = math.dist(cur, self._prev_cur)
            if moved > self.STALL_FRAC * step:
                self._jog_moved_once = True   # the EE is actually tracking now
        else:
            moved = step      # first tick: assume not stalled (IK still engaging)
        self._prev_cur = list(cur)

        # While latched at a limit, hold the target at the actual (reachable)
        # pose so the IK settles and Home/E-stop work. Release only when the EE
        # actually moves again or the user steers well off the stalled direction
        # (so jogging back into free space resumes immediately).
        if self._cart_stalled:
            dot = sum(d_unit[i] * self._stall_dir[i] for i in range(3))
            if moved >= self.STALL_FRAC * step or dot < self.UNSTALL_DOT:
                self._cart_stalled = False
                self._cart_stall = 0
            else:
                self._cart_target = list(cur)
                self._publish_ee_target(*cur)
                return

        # Build the leading target, clamped to within CART_LEAD_M of the actual,
        # then projected into the reachable dome (never outside the workspace).
        t = [self._cart_target[0] + dx,
             self._cart_target[1] + dy,
             self._cart_target[2] + dz]
        lead = self.CART_LEAD_M
        for i in range(3):
            t[i] = min(cur[i] + lead, max(cur[i] - lead, t[i]))
        t, _ = self._clamp_target(t, cur)

        # Stall detection: an outstanding lead the EE isn't closing ⇒ stuck.
        # Only after the EE has started moving, so the IK's cold-start latency
        # (a few ticks before the arm responds) can't be mistaken for a stall.
        gap = math.dist(cur, t)
        if gap > 0.5 * lead and moved < self.STALL_FRAC * step and self._jog_moved_once:
            self._cart_stall += 1
        else:
            self._cart_stall = 0
        if self._cart_stall >= self.STALL_TICKS:
            # Reach limit: hold the reachable pose so the IK settles and Home/
            # E-stop keep working. At the dome edge it's a true boundary; inside
            # the dome it's a local-IK limit (jog a different way / reconfigure
            # by hand) — either way the jog stops cleanly here.
            at_limit = self._at_workspace_boundary(cur)
            self._cart_stalled = True
            self._stall_dir = d_unit
            self._cart_target = list(cur)
            self._publish_ee_target(*cur)
            self.get_logger().info(
                "jog: at workspace limit — holding" if at_limit else
                "jog: reach limit here — jog another way to continue")
            return

        self._cart_target = t
        self._publish_ee_target(*t)

    def _cart_jog_stop(self, force: bool = False) -> None:
        """Re-anchor the Cartesian-jog target to the current actual pose so the
        live jog IK (ik_arm_v3) reaches it immediately and goes idle. Called when
        the joystick is released/centered and before a drawing is dispatched, so
        the jog IK can never keep streaming /joint_commands over another motion.
        Safe / cheap to call repeatedly. With force=True it always re-anchors
        (used before drawing / on freeze) — a hard guarantee the jog IK is idle
        even if the bridge thinks no jog is in progress; with force=False it is a
        no-op when no jog is active (the joystick-release path)."""
        if not force and self._cart_target is None and not self._cart_stalled:
            return
        if self._ee_pose is not None:
            p = self._ee_pose.pose.position
            self._publish_ee_target(p.x, p.y, p.z)
        self._cart_target = None
        self._prev_cur = None
        self._cart_stall = 0
        self._cart_stalled = False
        self._jog_moved_once = False

    # ── workspace clamp ───────────────────────────────────────────────────────
    def _clamp_target(self, t: list[float], cur: list[float]):
        """Project a jog target into the reachable dome (shrunk by _WS_MARGIN_M),
        but never inside the current actual pose — that pose is reachable by
        definition and the sampled model can under-reach by a few mm. Returns
        (clamped_xyz, was_clamped)."""
        x, y, z = t
        r = math.hypot(x, y)
        r_cur = math.hypot(cur[0], cur[1])
        z_lo = min(_WS_Z_MIN + _WS_MARGIN_M, cur[2])
        z_hi = max(_WS_Z_MAX - _WS_MARGIN_M, cur[2])
        zc = min(z_hi, max(z_lo, z))
        r_lim = max(reach_r_max(zc) - _WS_MARGIN_M, r_cur)
        clamped = zc != z
        if r > r_lim and r > 1e-9:
            s = r_lim / r
            x, y = x * s, y * s
            clamped = True
        return [x, y, zc], clamped

    def _at_workspace_boundary(self, pos: list[float], tol: float = 0.02) -> bool:
        """True if pos sits at the edge of the reachable dome — so a stall there
        is a genuine reach limit, not an interior local-IK dead end."""
        x, y, z = pos
        if z >= _WS_Z_MAX - tol or z <= _WS_Z_MIN + tol:
            return True
        return math.hypot(x, y) >= reach_r_max(z) - tol

    def set_cartesian(self, x: float, y: float, z: float) -> None:
        """Send the EE to an absolute (x,y,z) in the base frame, holding the
        current orientation. Backs the manual X/Y/Z set in Cartesian mode."""
        if self._estopped:
            self.get_logger().warn("E-stop active — set ignored")
            return
        if self._ee_pose is None:
            self.get_logger().warn("no /ee_pose yet — is the FK node running?")
            return
        cur = [self._ee_pose.pose.position.x,
               self._ee_pose.pose.position.y,
               self._ee_pose.pose.position.z]
        (x, y, z), clamped = self._clamp_target([x, y, z], cur)
        if clamped:
            self.get_logger().warn("SET ee target clamped into reachable workspace")
        self._cart_target = [x, y, z]  # keep jog continuous from the set point
        self._prev_cur = None
        self._cart_stall = 0
        self._cart_stalled = False
        self._jog_moved_once = False
        self._publish_ee_target(x, y, z)
        self.get_logger().info(f"SET ee -> ({x:+.3f}, {y:+.3f}, {z:+.3f}) m")

    # ── drawing ───────────────────────────────────────────────────────────
    def send_drawing(self, strokes_dict: dict) -> None:
        if self._estopped:
            self.get_logger().warn("E-stop active — drawing ignored")
            return
        # Defensive: make sure the live Cartesian-jog IK is idle before the batch
        # planner takes the controller, so a still-active jog can't preempt the
        # drawing trajectory (see _cart_jog_stop). force=True = hard guarantee.
        self._cart_jog_stop(force=True)
        msg = String()
        msg.data = json.dumps(strokes_dict)
        self.strokes_pub.publish(msg)
        self._last_drawing = msg.data
        n = len(strokes_dict.get("strokes", []))
        self.get_logger().info(f"published drawing: {n} strokes")

    def resend_last_drawing(self) -> None:
        if self._last_drawing is None:
            self.get_logger().warn("no previous drawing to resume")
            return
        msg = String()
        msg.data = self._last_drawing
        self.strokes_pub.publish(msg)

    # ── safety ────────────────────────────────────────────────────────────
    def freeze(self) -> None:
        """Preempt whatever the controller is doing and hold position."""
        self._cart_jog_stop(force=True)   # stop the jog IK fighting the hold trajectory
        self._clear_path()
        self._send_traj(list(self._last_q), 0.1)

    # ── hard E-stop: kill the nodes that drive the arm ─────────────────────
    def _find_node_procs(self, node_names):
        """Return [(pid, argv, cwd)] for OS processes whose ROS node name is in
        ``node_names`` (matched by the ``__node:=NAME`` remap or the executable
        basename). Excludes this GUI process. A node with no separate process —
        e.g. a ros2_control controller living inside Gazebo — simply isn't
        found, so it's skipped (we never kill Gazebo)."""
        mypid = os.getpid()
        out = []
        for cmd_path in glob.glob('/proc/[0-9]*/cmdline'):
            try:
                pid = int(cmd_path.split('/')[2])
                if pid == mypid:
                    continue
                with open(cmd_path, 'rb') as f:
                    argv = [a.decode('utf-8', 'replace')
                            for a in f.read().split(b'\x00') if a]
            except (OSError, ValueError):
                continue
            if not argv:
                continue
            joined = ' '.join(argv)
            bases = {a.rsplit('/', 1)[-1] for a in argv}
            for nm in node_names:
                if (f'__node:={nm}' in joined or nm in bases or f'{nm}.py' in bases):
                    try:
                        cwd = os.readlink(f'/proc/{pid}/cwd')
                    except OSError:
                        cwd = None
                    out.append((pid, argv, cwd))
                    break
        return out

    def estop(self) -> None:
        """HARD E-stop: kill every node driving the arm — the command drivers
        (IK / ik_to_trajectory / drawing planner) AND whatever publishes
        /joint_states — so the robot has nothing left to follow and simply
        stops where it is (a soft 'hold' command is useless when the arm is
        wobbling near a singularity and won't accept commands). The killed
        processes' command lines are saved so RESET can re-run them."""
        self._estopped = True
        self._cart_target = None       # forget any in-flight jog target
        self._prev_cur = None
        self._cart_stall = 0
        self._cart_stalled = False

        names = set(DRIVER_NODES)
        try:
            for info in self.get_publishers_info_by_topic('/joint_states'):
                if info.node_name and info.node_name != self.get_name():
                    names.add(info.node_name)
        except Exception as e:
            self.get_logger().warn(f"E-STOP: couldn't enumerate /joint_states publishers: {e}")

        procs = self._find_node_procs(names)
        self._killed_procs = [(argv, cwd) for (_p, argv, cwd) in procs]
        killed = 0
        for pid, argv, _cwd in procs:
            try:
                os.kill(pid, signal.SIGKILL)
                killed += 1
                self.get_logger().error(f"E-STOP killed pid {pid}: {argv[0].rsplit('/',1)[-1]} "
                                        f"{argv[1].rsplit('/',1)[-1] if len(argv) > 1 else ''}")
            except OSError as e:
                self.get_logger().warn(f"E-STOP: couldn't kill pid {pid}: {e}")

        # With the command flood now dead, a single hold trajectory STICKS
        # (nothing left to preempt it). This preempts any long drawing
        # trajectory still loaded in the controller so the arm freezes mid-
        # stroke instead of finishing it. In sim this halts the JTC at the
        # current pose; on hardware there's no JTC so it's a harmless no-op
        # (killing the /joint_states publisher is what holds the motors there).
        try:
            self._clear_path()
            self._send_traj(list(self._last_q), 0.1)
        except Exception as e:
            self.get_logger().warn(f"E-STOP: hold publish failed: {e}")

        self.get_logger().error(
            f"E-STOP engaged — killed {killed} driver node(s) + held current pose; "
            f"arm has no command source. Commands blocked until RESET.")

    def estop_reset(self) -> None:
        """RESET: re-run the nodes the E-stop killed, with this process's ROS
        environment. The arm STAYS where it is — the restarted IK seeds from the
        current /joint_states and won't move until commanded; nothing auto-homes."""
        n = 0
        for argv, cwd in getattr(self, '_killed_procs', []):
            try:
                subprocess.Popen(argv, cwd=cwd or None, env=os.environ.copy(),
                                 stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                                 start_new_session=True)
                n += 1
                self.get_logger().warn(f"RESET re-ran: {argv[0].rsplit('/',1)[-1]} "
                                       f"{argv[1].rsplit('/',1)[-1] if len(argv) > 1 else ''}")
            except OSError as e:
                self.get_logger().error(f"RESET: couldn't re-run {argv}: {e}")
        self._killed_procs = []
        self._estopped = False
        self.get_logger().warn(
            f"E-stop cleared — re-ran {n} node(s); arm holds its current pose "
            f"(press Home to move it).")
